name: Build and Deploy Tech Radar

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
          future: false
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure `release/` is included in `_site/`
        run: |
          if [ -d "docs/release" ]; then
            cp -r docs/release docs/_site/release
            echo "Copied release/ into _site/"
          else
            echo "WARNING: release/ directory does not exist!"
            exit 1
          fi

      - name: Find latest radar-x.x.js and copy it
        run: |
          LATEST_JS=$(ls -v docs/_site/release/radar-*.js 2>/dev/null | tail -n 1 || echo "")
          if [ -z "$LATEST_JS" ]; then
            echo "ERROR: No radar-x.x.js file found in docs/_site/release/"
            exit 1
          fi
          cp "$LATEST_JS" docs/_site/radar.js
          echo "Using $LATEST_JS as radar.js"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
