name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
          fetch-depth: 1

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
          name: github-pages
          retention-days: 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-archive
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  deploy:
    runs-on: ubuntu-24.04
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          preview: false

  report-build-status:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Report Build Status
        run: |
          gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: success
