name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
          fetch-depth: 1

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
          name: github-pages
          retention-days: 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
